### PR TITLE
Table optimizations

### PR DESCRIPTION
**Pull request by akvlad**

### CODE REVIEW

**Comment by akvlad** [comment]
# Changelog
New tables:
- `samples_v4`
added `labels` column with the labels. So no need to left join the time_series table.
- `time_series_gin`, `time_series_gin_view` to index key-value pairs of labels. 
- `samples_read_v4_1`, `samples_read_v4_2` to be compatible with samples_v3

# Migration to the current version. 
@Dletta Should be in https://github.com/lmangani/cLoki/wiki/Upgrade this page

## Index all the fingerprints to `time_series_gin`
```
INSERT INTO time_series_gin (date, key, val, fingerprint) 
SELECT date, pairs.1 as key, pairs.2 as val, fingerprint FROM time_series ARRAY JOIN JSONExtractKeysAndValues(time_series.labels, 'String') as pairs
```
## Copy the data to samples_v4
```
INSERT INTO samples_v4 (fingerprint, labels, timestamp_ns, value, string) 
SELECT samples_read_v2_2.fingerprint as fingerprint, 
     JSONExtractKeysAndValues(time_series.labels, 'String') as labels, 
     timestamp_ns, value, string 
FROM samples_read_v2_2 INNER ANY JOIN time_series ON time_series.fingerprint == samples_read_v2_2.fingerprint
```
## Drop table `samples_v3`
```
DROP TABLE samples_v3
```

**Comment by akvlad** [comment]
@Dletta you should double check alerting.
As well as everything. The changes are major.

**Comment by akvlad** [comment]
No need to resave all the alert rules. @Dletta please recheck

**Comment by Dletta** [comment]
@akvlad Confirmed no update was needed after updating.

**Review by Dletta — APPROVED** [review]

**Comment by Dletta** [comment]
Tests successful. PR approved, recommend moving to v3.X to indicate schema change.

**Comment by lmangani** [comment]
Target version 2.1.x

**Review by Dletta — APPROVED** [review]
Pending 1 test

**Comment by akvlad** [comment]
UPD! No migration anymore. We reverted all the changes demanding any migrations.

**Pull request merged**
