### PR TITLE
WIP: Tempo API

### PR DESCRIPTION
**Pull request by lmangani**
WIP Experimental Branch!

### Key Endpoints
- [x] [ingest](https://grafana.com/docs/tempo/latest/api_docs/#ingest)
  - [x] [ZIPKIN v2 JSON](https://zipkin.io/zipkin-api/) ([swagger](https://zipkin.io/zipkin-api/#/default/post_spans))
- [x] [query](https://grafana.com/docs/tempo/latest/api_docs/#query)
- [x] [search](https://grafana.com/docs/tempo/latest/api_docs/#search)
- [x] [tags/values](https://grafana.com/docs/tempo/latest/api_docs/#search-tags) (100% like labels in cloki)

### Development Notes

> Clickhouse prototype for OpenTelemetry output via MV from the system table:

https://clickhouse.com/docs/en/operations/opentelemetry/

> For testing, it is possible to setup the export using a materialized view with the URL engine over the [system.opentelemetry_span_log](https://clickhouse.com/docs/en/operations/system-tables/opentelemetry_span_log/) table, which would push the arriving log data to an HTTP endpoint of a trace collector. 

> For example, to push the minimal span data to cloki in Zipkin v2 JSON format:
```
CREATE MATERIALIZED VIEW default.zipkin_spans
ENGINE = URL('http://127.0.0.1:3100/api/v2/spans', 'JSONEachRow')
SETTINGS output_format_json_named_tuples_as_objects = 1,
    output_format_json_array_of_rows = 1 AS
SELECT
    lower(hex(reinterpretAsFixedString(trace_id))) AS traceId,
    lower(hex(parent_span_id)) AS parentId,
    lower(hex(span_id)) AS id,
    operation_name AS name,
    start_time_us AS timestamp,
    finish_time_us - start_time_us AS duration,
    cast(tuple('clickhouse'), 'Tuple(serviceName text)') AS localEndpoint,
    cast(tuple(
        attribute.values[indexOf(attribute.names, 'db.statement')]),
        'Tuple("db.statement" text)') AS tags
FROM system.opentelemetry_span_log
```

------

#### Insert
```
clickhouse-client -h 127.0.0.1 --password password  --opentelemetry_start_trace_probability=0.1 --query_id "a0c9f73a1c684e0ce66333477a3841bf-200" --query "select 1 from remote('127.0.0.1', system, one) format Null"

clickhouse-client -h 127.0.0.1 --password password -q "system flush logs"
```
#### Query
```
 SELECT lower(hex(reinterpretAsFixedString(trace_id))) AS traceId, lower(hex(parent_span_id)) AS parentId, lower(hex(span_id)) AS id, operation_name AS name, start_time_us AS timestamp, finish_time_us - start_time_us AS duration, cast(tuple('clickhouse'), 'Tuple(serviceName text)') AS localEndpoint, cast(tuple( attribute.values[indexOf(attribute.names, 'db.statement')]), 'Tuple("db.statement" text)') AS tags FROM system.opentelemetry_span_log Format JSONEachRow;
```
#### Results

```json
{"traceId":"79f4c7c1f24b54fed749e67a5e201531","parentId":"00","id":"d53d8a901d9e12b2","name":"query","timestamp":"1640562656376384","duration":"973","localEndpoint":["clickhouse"],"tags":["db.statement"]}
{"traceId":"79f4c7c1f24b54fed749e67a5e201531","parentId":"d53d8a901d9e12b2","id":"0873edda85ec9939","name":"TCPHandler","timestamp":"1640562656376332","duration":"1124","localEndpoint":["clickhouse"],"tags":[""]}
```

### CODE REVIEW

**Comment by lmangani** [comment]
Test Scenario:

#### Send Spans
```
curl -X POST http://localhost:3100/tempo/api/push -H 'Content-Type: application/json' -d '[{
 "id": "1234",
 "traceId": "d6e9329d67b6146b",
 "timestamp": '$(date +%s%N | cut -b1-16)',
 "duration": 100000,
 "name": "span from bash!",
 "tags": {
    "http.method": "GET",
    "http.path": "/api"
  },
  "localEndpoint": {
    "serviceName": "shell script"
  }
}]'
```
```
curl -X POST http://localhost:3100/tempo/api/push  -H 'Content-Type: application/json' -d '[{
 "id": "5678",
 "traceId": "d6e9329d67b6146b",
 "parentId": "1234",
 "timestamp": '$(date +%s%N | cut -b1-16)',
 "duration": 100000,
 "name": "child span from bash!",
  "localEndpoint": {
    "serviceName": "shell script"
  }
}]'
```

#### Query Spans
```
curl http://localhost:3100/api/traces/d6e9329d67b6146b
```

**Comment by lmangani** [comment]
Protobuf JSON Schema for Opentelemetry Trace/v1 responses with [validator](https://runkit.com/lmangani/61d0a90fcbcc4600088d5ea6)

```json
{
  "resourceSpans": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "shell script"
            }
          }
        ]
      },
      "instrumentationLibrarySpans": [
        {
          "instrumentationLibrary": {},
          "spans": [
            {
              "traceId": "AAAAAAAAAADW6TKdZ7YUag==",
              "spanId": "AAAAAAAAEjQ=",
              "name": "span from bash!",
              "startTimeUnixNano": "1640617863672218000",
              "endTimeUnixNano": "1640617863772218000",
              "attributes": [
                {
                  "key": "http.path",
                  "value": {
                    "stringValue": "/api"
                  }
                },
                {
                  "key": "http.method",
                  "value": {
                    "stringValue": "GET"
                  }
                },
                {
                  "key": "env",
                  "value": {
                    "stringValue": "prod"
                  }
                }
              ],
              "status": {}
            }
          ]
        }
      ]
    },
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "shell script"
            }
          }
        ]
      },
      "instrumentationLibrarySpans": [
        {
          "instrumentationLibrary": {},
          "spans": [
            {
              "traceId": "AAAAAAAAAADW6TKdZ7YUag==",
              "spanId": "AAAAAAAAVng=",
              "parentSpanId": "AAAAAAAAEjQ=",
              "name": "child span from bash!",
              "startTimeUnixNano": "1640617865768371000",
              "endTimeUnixNano": "1640617865868371000",
              "attributes": [
                {
                  "key": "env",
                  "value": {
                    "stringValue": "prod"
                  }
                }
              ],
              "status": {}
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by lmangani** [comment]
image

**Comment by lmangani** [comment]
image

**Comment by lmangani** [comment]
@Dletta please retest using a fresh deployment to make sure the new format produces the same results

**Comment by Dletta** [comment]
Ready for merge after testing and tests have been added

**Pull request merged**
