### PR TITLE
Configurable LIVE VIEW query

### PR DESCRIPTION
**Pull request by akvlad**
LIVE VIEW is hidden behind `EXPERIMENTAL=1` env variable

### CODE REVIEW

**Review by lmangani — APPROVED** [review]

**Comment by lmangani** [comment]
Is this still required after the main LIVE VIEW progress fix?

**Comment by derlaft** [comment]
> Is this still required after the main LIVE VIEW progress fix?

It looks to me that the main fix is in this PR (51c3a06)

**Comment by lmangani** [comment]
@akvlad I think we no longer need to hide this feature in EXPERIMENTAL mode with the current fix?

**Comment by lmangani** [comment]
@Dletta could you perform a quick test to confirm readyness

**Review by Dletta — APPROVED** [review]
Tested, working well

**Pull request merged**
