### PR TITLE
Update to latest Loki API

### PR DESCRIPTION
**Pull request by lmangani**

### CODE REVIEW

**Comment by lmangani** [comment]
Anyone out there willing to give this a try and provide some feedback?

**Comment by lmangani** [comment]
Anyone out there willing to give this a try and provide some feedback?

**Comment by Slach** [comment]
thanks a lot for your efforts!

**Comment by lmangani** [comment]
@Slach thanks to you for the support! if you get a chance to test it, let us know so we can iron out any problem. Basic insert via API and Grafana queries seem to work fine. 

NOTE: Still implementing other parts of the new API and protobuf support is unfortunately still broken - we need a special genius to convert the group definitions in a way nodejs could leverage.

**Pull request merged**
